config/routes.rb
Rails.application.routes.draw do
  resources :lists
  devise_for :users
  root to: "home#index"
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:list_name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class="container">
<div class="row align-items-center" data-aos="fade-down"data-aos-easing="linear"data-aos-duration="1500">
  
  <div class="col">
    <h2>NEVER GOES OUT OF STOCK!</h2><br><br>
    <% if user_signed_in?  && current_user.role != "admin" %>
      <div>
          <%= link_to 'Create Your List',  lists_path, :class => "register-button btn-lg" %> 
      </div>
    <% elsif user_signed_in? && current_user.role == "admin" %>
      <div>
        <%= link_to 'Add In Backend',  products_path, :class => "register-button btn-lg" %> 
      </div>
    <% else %>
      <div>
        <%= link_to 'Register Now',  new_user_registration_path, :class => "register-button btn-lg" %> 
      </div>
    <% end %>
  </div>

  <div class="col-md" id="image">
    <%= image_tag "homepage_image.jpg", :class => "home_image" %>
  </div>
 
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-light navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag "logo.png", :class => "style_image" %>
    </a>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          Logged in as <strong><%= current_user.email %></strong>.
        </li>
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </li>
      <% else %>
        <li class="nav-item">
          <div>
             <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryHelper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>    
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="card">
 <div class="card-body">
  <div class="field">
    <%= form.label :list_name %>
    <%= form.text_field :list_name %>
  </div>

  <div class="actions">
    <%= form.submit :class=> "btn btn-outline-success"%>
      </div> 
  </div>
  </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list,:class=> "btn btn-outline-warning" %> |
<%= link_to 'Back', lists_path,:class=> "btn btn-outline-warning" %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>List name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.list_name %></td>
        <td><%= link_to 'Show', products_path ,:class=> "btn btn-outline-danger"%></td>
        <%#<td><%= link_to 'Edit', edit_list_path(list)</td>%>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } ,:class=> "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path,:class=>"btn btn-warning btn-lg" %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path,:class=> "btn btn-outline-warning" %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
 <div class="card-header">
<p>
  <strong>List name:</strong>
  <%= @list.list_name %>
</p>
</div>

<%= link_to 'Edit', edit_list_path(@list) ,:class=> "btn btn-warning" %> |
<%= link_to 'Back', lists_path ,:class=> "btn btn-warning" %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class="card">
 <div class="card-body">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.number_field :price %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description %>
      </div>

      <div class="actions">
        <%= form.submit :class=> "btn btn-outline-success"%>
      </div> 
  </div>
  </div> 
<% end %>

app/views/products/_user_products.html.erb
<div class="container">
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text"><%= product.description %></p>
          <a href="#" class="btn btn-success">Add To Your List</a>
        </div>
      </div>
    </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product,:class=> "btn btn-outline-warning" %> 
<%= link_to 'Back', products_path,:class=> "btn btn-outline-warning" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? && current_user.role !="admin" %>
  <h2>Choose Your Products To  Create List!</h2>
  <% @products.each do |product| %>
    <div class="container"> 
      <div class="row">
         <%= render "user_products", :product => product %>
      </div>
   </div>
  <% end %>
<% else %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <% if current_user.role == "admin" %>
          <th colspan="3"></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= product.description %></td>
          <% if current_user.role == "admin" %>
            <td><%= link_to 'Show', product ,:class=> "btn btn-outline-danger" %></td>
            <td><%= link_to 'Edit', edit_product_path(product),:class=> "btn btn-outline-danger"  %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } ,:class=> "btn btn-outline-danger" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if current_user.role == "admin" %>
    <div class="d-grid gap-2 col-6 mx-auto">
      <%= link_to 'New Product', new_product_path,:class=>"btn btn-warning btn-lg"%>
    </div>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path ,:class=> "btn btn-outline-warning"%>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card">
 <div class="card-header">
    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>
 </div>
 <div class="card-body">
    <p class="card-text">
      <strong>Price:</strong>
      <%= @product.price %>
    </p>

    <p class="card-text">
      <strong>Description</strong>
      <%= @product.description %>
    </p>


<%= link_to 'Edit', edit_product_path(@product) ,:class=> "btn btn-warning"%> 
<%= link_to 'Back', products_path ,:class=> "btn btn-warning"%>